"""init admcondojet schema

Revision ID: 20260221_0001
Revises:
Create Date: 2026-02-21 00:00:00.000000
"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "20260221_0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(
        """
        CREATE SCHEMA IF NOT EXISTS admcondojet;
        SET search_path TO admcondojet, public;

        CREATE TYPE perfil_usuario AS ENUM ('ADMIN', 'PORTEIRO');
        CREATE TYPE tipo_endereco AS ENUM ('QUADRA_CONJUNTO_LOTE', 'QUADRA_SETOR_CHACARA');
        CREATE TYPE tipo_encomenda AS ENUM ('PACOTE', 'ENVELOPE', 'CAIXA');
        CREATE TYPE status_encomenda AS ENUM ('RECEBIDA', 'DISPONIVEL_RETIRADA', 'ENTREGUE');
        CREATE TYPE status_conexao_whatsapp AS ENUM ('DESCONECTADO', 'CONECTADO', 'ERRO');

        CREATE TABLE condominios (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          nome VARCHAR(150) NOT NULL,
          api_key VARCHAR(120) NOT NULL UNIQUE,
          ativo BOOLEAN NOT NULL DEFAULT TRUE,
          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
          updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
          CONSTRAINT ck_condominio_nome_nao_vazio CHECK (BTRIM(nome) <> '')
        );

        CREATE SEQUENCE seq_encomenda_codigo START WITH 1 INCREMENT BY 1;

        CREATE TABLE enderecos (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          condominio_id BIGINT NOT NULL REFERENCES condominios(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
          tipo_endereco tipo_endereco NOT NULL,
          quadra VARCHAR(20) NOT NULL,
          conjunto VARCHAR(20),
          lote VARCHAR(20),
          setor_chacara VARCHAR(80),
          numero_chacara VARCHAR(20),
          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
          updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
          CONSTRAINT ck_endereco_campos_tipo_1 CHECK (
            tipo_endereco <> 'QUADRA_CONJUNTO_LOTE'
            OR (conjunto IS NOT NULL AND lote IS NOT NULL AND setor_chacara IS NULL AND numero_chacara IS NULL)
          ),
          CONSTRAINT ck_endereco_campos_tipo_2 CHECK (
            tipo_endereco <> 'QUADRA_SETOR_CHACARA'
            OR (setor_chacara IS NOT NULL AND numero_chacara IS NOT NULL AND conjunto IS NULL AND lote IS NULL)
          ),
          CONSTRAINT uq_enderecos_id_condominio UNIQUE (id, condominio_id)
        );

        CREATE TABLE usuarios (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          condominio_id BIGINT NOT NULL REFERENCES condominios(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
          nome VARCHAR(120) NOT NULL,
          email VARCHAR(255) NOT NULL,
          telefone VARCHAR(15) NOT NULL,
          senha_hash TEXT NOT NULL,
          perfil perfil_usuario NOT NULL,
          responsavel_sistema BOOLEAN NOT NULL DEFAULT FALSE,
          ativo BOOLEAN NOT NULL DEFAULT TRUE,
          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
          updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
          CONSTRAINT ck_usuario_nome_nao_vazio CHECK (BTRIM(nome) <> ''),
          CONSTRAINT ck_usuario_telefone_formato CHECK (telefone ~ '^\\(\\d{2}\\)\\s\\d{5}-\\d{4}$'),
          CONSTRAINT ck_usuario_responsavel_apenas_admin CHECK (perfil = 'ADMIN' OR responsavel_sistema = FALSE),
          CONSTRAINT uq_usuarios_id_condominio UNIQUE (id, condominio_id)
        );

        CREATE TABLE moradores (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          condominio_id BIGINT NOT NULL REFERENCES condominios(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
          nome VARCHAR(120) NOT NULL,
          telefone VARCHAR(30) NOT NULL,
          email VARCHAR(255) NOT NULL,
          endereco_id BIGINT NOT NULL,
          senha_hash TEXT NOT NULL,
          ativo BOOLEAN NOT NULL DEFAULT TRUE,
          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
          updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
          CONSTRAINT ck_morador_nome_nao_vazio CHECK (BTRIM(nome) <> ''),
          CONSTRAINT ck_morador_telefone_nao_vazio CHECK (BTRIM(telefone) <> ''),
          CONSTRAINT uq_morador_id_endereco_condominio UNIQUE (id, endereco_id, condominio_id),
          CONSTRAINT fk_morador_endereco_condominio FOREIGN KEY (endereco_id, condominio_id)
            REFERENCES enderecos(id, condominio_id)
            ON UPDATE RESTRICT ON DELETE RESTRICT
        );

        CREATE TABLE encomendas (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          condominio_id BIGINT NOT NULL REFERENCES condominios(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
          codigo_interno VARCHAR(24) NOT NULL UNIQUE DEFAULT ('ENC-' || LPAD(NEXTVAL('seq_encomenda_codigo')::TEXT, 10, '0')),
          codigo_externo VARCHAR(100),
          descricao TEXT,
          tipo tipo_encomenda NOT NULL,
          empresa_entregadora VARCHAR(120),
          endereco_id BIGINT NOT NULL,
          morador_id BIGINT NOT NULL,
          status status_encomenda NOT NULL DEFAULT 'RECEBIDA',
          data_recebimento DATE NOT NULL,
          hora_recebimento TIME NOT NULL,
          recebido_por_usuario_id BIGINT NOT NULL,
          data_entrega TIMESTAMPTZ,
          entregue_por_usuario_id BIGINT,
          retirado_por_nome VARCHAR(120),
          motivo_reabertura TEXT,
          reaberto_por_usuario_id BIGINT,
          reaberto_em TIMESTAMPTZ,
          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
          updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
          CONSTRAINT fk_encomenda_morador_endereco_condominio FOREIGN KEY (morador_id, endereco_id, condominio_id)
            REFERENCES moradores(id, endereco_id, condominio_id)
            ON UPDATE RESTRICT ON DELETE RESTRICT,
          CONSTRAINT fk_encomenda_recebido_por_condominio FOREIGN KEY (recebido_por_usuario_id, condominio_id)
            REFERENCES usuarios(id, condominio_id)
            ON UPDATE RESTRICT ON DELETE RESTRICT,
          CONSTRAINT fk_encomenda_entregue_por_condominio FOREIGN KEY (entregue_por_usuario_id, condominio_id)
            REFERENCES usuarios(id, condominio_id)
            ON UPDATE RESTRICT ON DELETE RESTRICT,
          CONSTRAINT fk_encomenda_reaberto_por_condominio FOREIGN KEY (reaberto_por_usuario_id, condominio_id)
            REFERENCES usuarios(id, condominio_id)
            ON UPDATE RESTRICT ON DELETE RESTRICT,
          CONSTRAINT ck_encomenda_entrega_consistente CHECK (
            (
              status = 'ENTREGUE'
              AND data_entrega IS NOT NULL
              AND entregue_por_usuario_id IS NOT NULL
              AND BTRIM(COALESCE(retirado_por_nome, '')) <> ''
              AND motivo_reabertura IS NULL
              AND reaberto_por_usuario_id IS NULL
              AND reaberto_em IS NULL
            )
            OR (
              status = 'DISPONIVEL_RETIRADA'
              AND data_entrega IS NULL
              AND entregue_por_usuario_id IS NULL
              AND retirado_por_nome IS NULL
              AND (
                (motivo_reabertura IS NULL AND reaberto_por_usuario_id IS NULL AND reaberto_em IS NULL)
                OR
                (BTRIM(COALESCE(motivo_reabertura, '')) <> '' AND reaberto_por_usuario_id IS NOT NULL AND reaberto_em IS NOT NULL)
              )
            )
            OR (
              status = 'RECEBIDA'
              AND data_entrega IS NULL
              AND entregue_por_usuario_id IS NULL
              AND retirado_por_nome IS NULL
              AND motivo_reabertura IS NULL
              AND reaberto_por_usuario_id IS NULL
              AND reaberto_em IS NULL
            )
          )
        );

        CREATE TABLE configuracoes (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          condominio_id BIGINT NOT NULL REFERENCES condominios(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
          whatsapp_token TEXT,
          numero_condominio VARCHAR(30),
          status_conexao status_conexao_whatsapp NOT NULL DEFAULT 'DESCONECTADO',
          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
          updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
        );

        CREATE OR REPLACE FUNCTION fn_set_updated_at() RETURNS TRIGGER AS $$
        BEGIN
          NEW.updated_at = NOW();
          RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;

        CREATE OR REPLACE FUNCTION fn_prevent_delete_encomenda_entregue() RETURNS TRIGGER AS $$
        BEGIN
          IF OLD.status = 'ENTREGUE' THEN
            RAISE EXCEPTION 'Nao e permitido excluir encomenda com status ENTREGUE (id=%).', OLD.id;
          END IF;
          RETURN OLD;
        END;
        $$ LANGUAGE plpgsql;

        CREATE OR REPLACE FUNCTION fn_validate_encomenda_status_transition() RETURNS TRIGGER AS $$
        BEGIN
          IF OLD.status = 'ENTREGUE' AND NEW.status = 'RECEBIDA' THEN
            RAISE EXCEPTION 'Nao e permitido reverter status de ENTREGUE para RECEBIDA (id=%).', OLD.id;
          END IF;

          IF OLD.status = 'ENTREGUE' AND NEW.status = 'DISPONIVEL_RETIRADA' THEN
            IF BTRIM(COALESCE(NEW.motivo_reabertura, '')) = '' OR NEW.reaberto_por_usuario_id IS NULL THEN
              RAISE EXCEPTION 'Reabertura requer motivo_reabertura e reaberto_por_usuario_id (id=%).', OLD.id;
            END IF;
            NEW.data_entrega = NULL;
            NEW.entregue_por_usuario_id = NULL;
            NEW.retirado_por_nome = NULL;
            IF NEW.reaberto_em IS NULL THEN
              NEW.reaberto_em = NOW();
            END IF;
          END IF;

          IF NEW.status = 'ENTREGUE' THEN
            NEW.motivo_reabertura = NULL;
            NEW.reaberto_por_usuario_id = NULL;
            NEW.reaberto_em = NULL;
          END IF;

          RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;

        CREATE TRIGGER trg_condominios_updated_at
        BEFORE UPDATE ON condominios
        FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

        CREATE TRIGGER trg_enderecos_updated_at
        BEFORE UPDATE ON enderecos
        FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

        CREATE TRIGGER trg_usuarios_updated_at
        BEFORE UPDATE ON usuarios
        FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

        CREATE TRIGGER trg_moradores_updated_at
        BEFORE UPDATE ON moradores
        FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

        CREATE TRIGGER trg_encomendas_updated_at
        BEFORE UPDATE ON encomendas
        FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

        CREATE TRIGGER trg_configuracoes_updated_at
        BEFORE UPDATE ON configuracoes
        FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

        CREATE TRIGGER trg_no_delete_encomenda_entregue
        BEFORE DELETE ON encomendas
        FOR EACH ROW EXECUTE FUNCTION fn_prevent_delete_encomenda_entregue();

        CREATE TRIGGER trg_validate_encomenda_status_transition
        BEFORE UPDATE ON encomendas
        FOR EACH ROW EXECUTE FUNCTION fn_validate_encomenda_status_transition();

        CREATE UNIQUE INDEX ux_enderecos_tipo1_condominio
          ON enderecos (condominio_id, quadra, conjunto, lote)
          WHERE tipo_endereco = 'QUADRA_CONJUNTO_LOTE';

        CREATE UNIQUE INDEX ux_enderecos_tipo2_condominio
          ON enderecos (condominio_id, quadra, setor_chacara, numero_chacara)
          WHERE tipo_endereco = 'QUADRA_SETOR_CHACARA';

        CREATE UNIQUE INDEX ux_usuarios_condominio_email_lower ON usuarios (condominio_id, (LOWER(email)));
        CREATE UNIQUE INDEX ux_usuarios_responsavel_por_condominio ON usuarios (condominio_id) WHERE responsavel_sistema = TRUE;
        CREATE UNIQUE INDEX ux_moradores_condominio_email_lower ON moradores (condominio_id, (LOWER(email)));
        CREATE UNIQUE INDEX ux_configuracoes_por_condominio ON configuracoes (condominio_id);

        CREATE INDEX idx_enderecos_condominio ON enderecos(condominio_id);
        CREATE INDEX idx_usuarios_condominio ON usuarios(condominio_id);
        CREATE INDEX idx_moradores_condominio ON moradores(condominio_id);
        CREATE INDEX idx_moradores_endereco_ativo ON moradores(endereco_id, condominio_id) WHERE ativo = TRUE;
        CREATE INDEX idx_encomendas_condominio_status ON encomendas(condominio_id, status);
        CREATE INDEX idx_encomendas_status_data_recebimento ON encomendas(status, data_recebimento DESC);
        CREATE INDEX idx_encomendas_morador_status ON encomendas(morador_id, status);
        CREATE INDEX idx_encomendas_endereco_status ON encomendas(endereco_id, status);
        CREATE INDEX idx_encomendas_data_entrega ON encomendas(data_entrega DESC) WHERE status = 'ENTREGUE';

        INSERT INTO condominios (nome, api_key, ativo)
        VALUES ('Condominio Padrao', 'condojet-default-api-key', TRUE);
        """
    )


def downgrade() -> None:
    op.execute("DROP SCHEMA IF EXISTS admcondojet CASCADE;")
