"""base da refatoracao de enderecamento por tipo de condominio

Revision ID: 20260307_0014
Revises: 20260304_0013
Create Date: 2026-03-07 21:00:00.000000
"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "20260307_0014"
down_revision: Union[str, None] = "20260304_0013"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(
        """
        SET search_path TO admcondojet, public;

        CREATE TABLE IF NOT EXISTS tipos_condominio (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          nome VARCHAR(120) NOT NULL,
          slug VARCHAR(40) NOT NULL,
          ativo BOOLEAN NOT NULL DEFAULT TRUE,
          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
          updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
          CONSTRAINT uq_tipos_condominio_nome UNIQUE (nome),
          CONSTRAINT uq_tipos_condominio_slug UNIQUE (slug),
          CONSTRAINT ck_tipos_condominio_nome_nao_vazio CHECK (BTRIM(nome) <> ''),
          CONSTRAINT ck_tipos_condominio_slug_nao_vazio CHECK (BTRIM(slug) <> '')
        );

        CREATE TABLE IF NOT EXISTS tipos_logradouro_horizontal (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          nome VARCHAR(80) NOT NULL,
          slug VARCHAR(40) NOT NULL,
          ativo BOOLEAN NOT NULL DEFAULT TRUE,
          ordem_exibicao BIGINT NOT NULL DEFAULT 100,
          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
          updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
          CONSTRAINT uq_tipos_logradouro_horizontal_nome UNIQUE (nome),
          CONSTRAINT uq_tipos_logradouro_horizontal_slug UNIQUE (slug),
          CONSTRAINT ck_tipos_logradouro_horizontal_nome_nao_vazio CHECK (BTRIM(nome) <> ''),
          CONSTRAINT ck_tipos_logradouro_horizontal_slug_nao_vazio CHECK (BTRIM(slug) <> '')
        );

        CREATE TABLE IF NOT EXISTS subtipos_logradouro_horizontal (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          tipo_logradouro_horizontal_id BIGINT NOT NULL
            REFERENCES tipos_logradouro_horizontal(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
          nome VARCHAR(80) NOT NULL,
          slug VARCHAR(40) NOT NULL,
          ativo BOOLEAN NOT NULL DEFAULT TRUE,
          ordem_exibicao BIGINT NOT NULL DEFAULT 100,
          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
          updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
          CONSTRAINT uq_subtipos_logradouro_horizontal_tipo_nome UNIQUE (tipo_logradouro_horizontal_id, nome),
          CONSTRAINT uq_subtipos_logradouro_horizontal_tipo_slug UNIQUE (tipo_logradouro_horizontal_id, slug),
          CONSTRAINT ck_subtipos_logradouro_horizontal_nome_nao_vazio CHECK (BTRIM(nome) <> ''),
          CONSTRAINT ck_subtipos_logradouro_horizontal_slug_nao_vazio CHECK (BTRIM(slug) <> '')
        );

        ALTER TABLE condominios
          ADD COLUMN IF NOT EXISTS tipo_condominio_id BIGINT;

        ALTER TABLE condominios
          DROP CONSTRAINT IF EXISTS fk_condominios_tipo_condominio;

        ALTER TABLE condominios
          ADD CONSTRAINT fk_condominios_tipo_condominio
          FOREIGN KEY (tipo_condominio_id)
          REFERENCES tipos_condominio(id)
          ON UPDATE RESTRICT ON DELETE RESTRICT;

        CREATE TABLE IF NOT EXISTS enderecos_morador (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          condominio_id BIGINT NOT NULL
            REFERENCES condominios(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
          tipo_condominio_id BIGINT NOT NULL
            REFERENCES tipos_condominio(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
          bloco VARCHAR(30),
          andar VARCHAR(20),
          apartamento VARCHAR(30),
          tipo_logradouro_horizontal_id BIGINT
            REFERENCES tipos_logradouro_horizontal(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
          subtipo_logradouro_horizontal_id BIGINT
            REFERENCES subtipos_logradouro_horizontal(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
          numero VARCHAR(30),
          ativo BOOLEAN NOT NULL DEFAULT TRUE,
          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
          updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
          CONSTRAINT uq_enderecos_morador_id_condominio UNIQUE (id, condominio_id)
        );

        CREATE INDEX IF NOT EXISTS idx_enderecos_morador_condominio_tipo
          ON enderecos_morador (condominio_id, tipo_condominio_id);

        CREATE INDEX IF NOT EXISTS idx_enderecos_morador_predio
          ON enderecos_morador (condominio_id, bloco, andar, apartamento)
          WHERE bloco IS NOT NULL AND andar IS NOT NULL AND apartamento IS NOT NULL;

        CREATE INDEX IF NOT EXISTS idx_enderecos_morador_horizontal
          ON enderecos_morador (condominio_id, tipo_logradouro_horizontal_id, subtipo_logradouro_horizontal_id, numero)
          WHERE tipo_logradouro_horizontal_id IS NOT NULL
            AND subtipo_logradouro_horizontal_id IS NOT NULL
            AND numero IS NOT NULL;

        DROP TRIGGER IF EXISTS trg_tipos_condominio_updated_at ON tipos_condominio;
        CREATE TRIGGER trg_tipos_condominio_updated_at
        BEFORE UPDATE ON tipos_condominio
        FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

        DROP TRIGGER IF EXISTS trg_tipos_logradouro_horizontal_updated_at ON tipos_logradouro_horizontal;
        CREATE TRIGGER trg_tipos_logradouro_horizontal_updated_at
        BEFORE UPDATE ON tipos_logradouro_horizontal
        FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

        DROP TRIGGER IF EXISTS trg_subtipos_logradouro_horizontal_updated_at ON subtipos_logradouro_horizontal;
        CREATE TRIGGER trg_subtipos_logradouro_horizontal_updated_at
        BEFORE UPDATE ON subtipos_logradouro_horizontal
        FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

        DROP TRIGGER IF EXISTS trg_enderecos_morador_updated_at ON enderecos_morador;
        CREATE TRIGGER trg_enderecos_morador_updated_at
        BEFORE UPDATE ON enderecos_morador
        FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

        INSERT INTO tipos_condominio (id, nome, slug, ativo)
        VALUES
          (1, 'Condominio Horizontal', 'HORIZONTAL', TRUE),
          (2, 'Predio/Conjunto Residencial', 'PREDIO_CONJUNTO', TRUE)
        ON CONFLICT (id) DO UPDATE
          SET nome = EXCLUDED.nome,
              slug = EXCLUDED.slug,
              ativo = EXCLUDED.ativo;

        INSERT INTO tipos_logradouro_horizontal (id, nome, slug, ativo, ordem_exibicao)
        VALUES
          (1, 'Trecho', 'TRECHO', TRUE, 10),
          (2, 'Quadra', 'QUADRA', TRUE, 20),
          (3, 'Etapa', 'ETAPA', TRUE, 30),
          (4, 'Area', 'AREA', TRUE, 40)
        ON CONFLICT (id) DO UPDATE
          SET nome = EXCLUDED.nome,
              slug = EXCLUDED.slug,
              ativo = EXCLUDED.ativo,
              ordem_exibicao = EXCLUDED.ordem_exibicao;

        INSERT INTO subtipos_logradouro_horizontal (tipo_logradouro_horizontal_id, nome, slug, ativo, ordem_exibicao)
        SELECT t.id, s.nome, s.slug, TRUE, s.ordem
          FROM tipos_logradouro_horizontal t
          CROSS JOIN (
            VALUES
              ('Conjunto', 'CONJUNTO', 10),
              ('Chacara', 'CHACARA', 20),
              ('Quadra', 'QUADRA', 30),
              ('Area Especial', 'AREA_ESPECIAL', 40)
          ) AS s(nome, slug, ordem)
        ON CONFLICT (tipo_logradouro_horizontal_id, slug) DO UPDATE
          SET nome = EXCLUDED.nome,
              ativo = EXCLUDED.ativo,
              ordem_exibicao = EXCLUDED.ordem_exibicao;

        SELECT setval(
          pg_get_serial_sequence('admcondojet.tipos_condominio', 'id'),
          COALESCE((SELECT MAX(id) FROM tipos_condominio), 1),
          TRUE
        );

        SELECT setval(
          pg_get_serial_sequence('admcondojet.tipos_logradouro_horizontal', 'id'),
          COALESCE((SELECT MAX(id) FROM tipos_logradouro_horizontal), 1),
          TRUE
        );
        """
    )


def downgrade() -> None:
    op.execute(
        """
        SET search_path TO admcondojet, public;

        DROP TRIGGER IF EXISTS trg_enderecos_morador_updated_at ON enderecos_morador;
        DROP TRIGGER IF EXISTS trg_subtipos_logradouro_horizontal_updated_at ON subtipos_logradouro_horizontal;
        DROP TRIGGER IF EXISTS trg_tipos_logradouro_horizontal_updated_at ON tipos_logradouro_horizontal;
        DROP TRIGGER IF EXISTS trg_tipos_condominio_updated_at ON tipos_condominio;

        DROP TABLE IF EXISTS enderecos_morador;
        DROP TABLE IF EXISTS subtipos_logradouro_horizontal;
        DROP TABLE IF EXISTS tipos_logradouro_horizontal;

        ALTER TABLE condominios DROP CONSTRAINT IF EXISTS fk_condominios_tipo_condominio;
        ALTER TABLE condominios DROP COLUMN IF EXISTS tipo_condominio_id;

        DROP TABLE IF EXISTS tipos_condominio;
        """
    )
