"""move whatsapp webhooks to global scope

Revision ID: 20260303_0011
Revises: 20260303_0010
Create Date: 2026-03-03 16:00:00.000000
"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "20260303_0011"
down_revision: Union[str, None] = "20260303_0010"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS admcondojet.webhooks_n8n_global (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          tipo VARCHAR(32) NOT NULL,
          url TEXT NOT NULL,
          ativo BOOLEAN NOT NULL DEFAULT TRUE,
          updated_by_usuario_id BIGINT NULL,
          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
          updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
          CONSTRAINT ck_webhooks_n8n_global_tipo_valido CHECK (tipo IN ('whatsapp_create', 'whatsapp_query')),
          CONSTRAINT ck_webhooks_n8n_global_url_nao_vazia CHECK (BTRIM(url) <> ''),
          CONSTRAINT uq_webhooks_n8n_global_tipo UNIQUE (tipo)
        );

        CREATE INDEX IF NOT EXISTS ix_webhooks_n8n_global_tipo
          ON admcondojet.webhooks_n8n_global (tipo);

        DROP TRIGGER IF EXISTS trg_webhooks_n8n_global_updated_at
          ON admcondojet.webhooks_n8n_global;

        CREATE TRIGGER trg_webhooks_n8n_global_updated_at
        BEFORE UPDATE ON admcondojet.webhooks_n8n_global
        FOR EACH ROW EXECUTE FUNCTION admcondojet.fn_set_updated_at();

        INSERT INTO admcondojet.webhooks_n8n_global (tipo, url, ativo, updated_by_usuario_id, created_at, updated_at)
        SELECT src.tipo, src.url, src.ativo, src.updated_by_usuario_id, src.created_at, src.updated_at
        FROM (
          SELECT DISTINCT ON (w.tipo)
            w.tipo,
            w.url,
            w.ativo,
            w.updated_by_usuario_id,
            w.created_at,
            w.updated_at
          FROM admcondojet.webhooks_n8n_condominio w
          ORDER BY w.tipo, w.updated_at DESC, w.id DESC
        ) AS src
        ON CONFLICT (tipo) DO UPDATE
        SET
          url = EXCLUDED.url,
          ativo = EXCLUDED.ativo,
          updated_by_usuario_id = EXCLUDED.updated_by_usuario_id,
          updated_at = EXCLUDED.updated_at;

        DROP TRIGGER IF EXISTS trg_webhooks_n8n_condominio_updated_at
          ON admcondojet.webhooks_n8n_condominio;

        DROP TABLE IF EXISTS admcondojet.webhooks_n8n_condominio;
        """
    )


def downgrade() -> None:
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS admcondojet.webhooks_n8n_condominio (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          condominio_id BIGINT NOT NULL REFERENCES admcondojet.condominios(id),
          tipo VARCHAR(32) NOT NULL,
          url TEXT NOT NULL,
          ativo BOOLEAN NOT NULL DEFAULT TRUE,
          updated_by_usuario_id BIGINT NULL,
          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
          updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
          CONSTRAINT ck_webhooks_n8n_tipo_valido CHECK (tipo IN ('whatsapp_create', 'whatsapp_query')),
          CONSTRAINT ck_webhooks_n8n_url_nao_vazia CHECK (BTRIM(url) <> ''),
          CONSTRAINT uq_webhooks_n8n_condominio_tipo UNIQUE (condominio_id, tipo)
        );

        CREATE INDEX IF NOT EXISTS ix_webhooks_n8n_condominio_id
          ON admcondojet.webhooks_n8n_condominio (condominio_id);

        DROP TRIGGER IF EXISTS trg_webhooks_n8n_condominio_updated_at
          ON admcondojet.webhooks_n8n_condominio;

        CREATE TRIGGER trg_webhooks_n8n_condominio_updated_at
        BEFORE UPDATE ON admcondojet.webhooks_n8n_condominio
        FOR EACH ROW EXECUTE FUNCTION admcondojet.fn_set_updated_at();

        DROP TRIGGER IF EXISTS trg_webhooks_n8n_global_updated_at
          ON admcondojet.webhooks_n8n_global;

        DROP TABLE IF EXISTS admcondojet.webhooks_n8n_global;
        """
    )
