"""create global responsible companies catalog

Revision ID: 20260303_0008
Revises: 20260302_0007
Create Date: 2026-03-03 00:00:00.000000
"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "20260303_0008"
down_revision: Union[str, None] = "20260302_0007"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS admcondojet.empresas_responsaveis_globais (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          nome VARCHAR(120) NOT NULL,
          nome_normalizado VARCHAR(120) NOT NULL,
          ativo BOOLEAN NOT NULL DEFAULT TRUE,
          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
          updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
          CONSTRAINT ck_empresas_responsaveis_globais_nome_nao_vazio CHECK (BTRIM(nome) <> ''),
          CONSTRAINT uq_empresas_responsaveis_globais_nome_normalizado UNIQUE (nome_normalizado)
        );

        DROP TRIGGER IF EXISTS trg_empresas_responsaveis_globais_updated_at
        ON admcondojet.empresas_responsaveis_globais;

        CREATE TRIGGER trg_empresas_responsaveis_globais_updated_at
        BEFORE UPDATE ON admcondojet.empresas_responsaveis_globais
        FOR EACH ROW EXECUTE FUNCTION admcondojet.fn_set_updated_at();
        """
    )


def downgrade() -> None:
    op.execute(
        """
        DROP TRIGGER IF EXISTS trg_empresas_responsaveis_globais_updated_at
        ON admcondojet.empresas_responsaveis_globais;

        DROP TABLE IF EXISTS admcondojet.empresas_responsaveis_globais;
        """
    )
