"""add global admin users table

Revision ID: 20260222_0003
Revises: 20260222_0002
Create Date: 2026-02-22 00:30:00.000000
"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "20260222_0003"
down_revision: Union[str, None] = "20260222_0002"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(
        """
        SET search_path TO admcondojet, public;

        DO $$
        BEGIN
          IF NOT EXISTS (
            SELECT 1
            FROM pg_type t
            JOIN pg_namespace n ON n.oid = t.typnamespace
            WHERE t.typname = 'perfil_global_usuario'
              AND n.nspname = 'admcondojet'
          ) THEN
            CREATE TYPE perfil_global_usuario AS ENUM ('ADMIN_GLOBAL');
          END IF;
        END$$;

        CREATE TABLE IF NOT EXISTS usuarios_globais (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          nome VARCHAR(120) NOT NULL,
          email VARCHAR(255) NOT NULL,
          senha_hash TEXT NOT NULL,
          perfil perfil_global_usuario NOT NULL DEFAULT 'ADMIN_GLOBAL',
          ativo BOOLEAN NOT NULL DEFAULT TRUE,
          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
          updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
          CONSTRAINT ck_usuario_global_nome_nao_vazio CHECK (BTRIM(nome) <> '')
        );

        DO $$
        BEGIN
          IF NOT EXISTS (
            SELECT 1
            FROM pg_trigger
            WHERE tgname = 'trg_usuarios_globais_updated_at'
          ) THEN
            CREATE TRIGGER trg_usuarios_globais_updated_at
            BEFORE UPDATE ON usuarios_globais
            FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();
          END IF;
        END$$;

        CREATE UNIQUE INDEX IF NOT EXISTS ux_usuarios_globais_email_lower ON usuarios_globais ((LOWER(email)));
        CREATE INDEX IF NOT EXISTS idx_usuarios_globais_ativo ON usuarios_globais(ativo);
        """
    )


def downgrade() -> None:
    op.execute(
        """
        SET search_path TO admcondojet, public;

        DROP INDEX IF EXISTS idx_usuarios_globais_ativo;
        DROP INDEX IF EXISTS ux_usuarios_globais_email_lower;
        DROP TABLE IF EXISTS usuarios_globais;
        DROP TYPE IF EXISTS perfil_global_usuario;
        """
    )
