"""add global api key store table

Revision ID: 20260222_0002
Revises: 20260221_0001
Create Date: 2026-02-22 00:00:00.000000
"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "20260222_0002"
down_revision: Union[str, None] = "20260221_0001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(
        """
        SET search_path TO admcondojet, public;

        CREATE TABLE IF NOT EXISTS chaves_sistema (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          nome VARCHAR(80) NOT NULL,
          valor VARCHAR(180) NOT NULL,
          ativo BOOLEAN NOT NULL DEFAULT TRUE,
          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
          updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
          CONSTRAINT uq_chaves_sistema_nome UNIQUE (nome),
          CONSTRAINT ck_chaves_sistema_nome_nao_vazio CHECK (BTRIM(nome) <> ''),
          CONSTRAINT ck_chaves_sistema_valor_nao_vazio CHECK (BTRIM(valor) <> '')
        );

        DO $$
        BEGIN
          IF NOT EXISTS (
            SELECT 1
            FROM pg_trigger
            WHERE tgname = 'trg_chaves_sistema_updated_at'
          ) THEN
            CREATE TRIGGER trg_chaves_sistema_updated_at
            BEFORE UPDATE ON chaves_sistema
            FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();
          END IF;
        END$$;

        CREATE UNIQUE INDEX IF NOT EXISTS ux_chaves_sistema_nome ON chaves_sistema (nome);

        INSERT INTO chaves_sistema (nome, valor, ativo)
        VALUES ('GLOBAL_API_KEY', 'change-me-global-key', TRUE)
        ON CONFLICT (nome) DO NOTHING;
        """
    )


def downgrade() -> None:
    op.execute(
        """
        SET search_path TO admcondojet, public;
        DROP INDEX IF EXISTS ux_chaves_sistema_nome;
        DROP TABLE IF EXISTS chaves_sistema;
        """
    )
